### ISSUE TITLE
Doesn't seem to work half the time?

### ISSUE THREAD

**Issue by flappybirdplayer29** [FroggerHH/MuckAchievements#3]
I add the achievement name and correct number according to #2 , yet it only works rarely. I do the same thing as with the ones that work and it simply doesn't add it or set the number. am I doing something wrong or it this mod just finnicky?

**Comment by FroggerHH** [comment]
Sure you doing it right. But it also works rarely for me. Idk why. 

Btw keep in mind that the achievement name you see in Steam is not always that name that is required. Coz name tht is needed is kind of id and not always the same as display name.
